# Lista do R9

## Importar planilha e definir data

In [ ]:
import pandas as pd
import numpy as np
import datetime

URL = "https://docs.google.com/spreadsheets/d/e/2PACX-1vToCjC7PtwrQtj6sNWHCmg6t_rH9R0CqHRlPhe3JqeurycvB1ETJ92mEbW0mub_n3L3Zl-Fz55yYSw5/pub?gid=419088388&single=true&output=csv"

print(URL)

# Get next wednesday date
proxima_quarta = datetime.date.today()
while proxima_quarta.weekday() != 2:
      proxima_quarta += datetime.timedelta(1)

# def get_data_sheet(googleSheetId, worksheetName):
#   return pd.read_csv('https://docs.google.com/spreadsheets/d/{0}/gviz/tq?tqx=out:csv&sheet={1}'.format(googleSheetId, worksheetName)) # my_googleSheetId = "1SPDEua-vEaDs5IXddDwrL2UhfmcJF2K4khTL2zd88Lc" # my_worksheetName = "1734190620" # data_sheet_raw = get_data_sheet(googleSheetId = my_googleSheetId, worksheetName = my_worksheetName)

data_sheet_raw = pd.read_csv(URL)
data_sheet_raw = data_sheet_raw.sort_values(by='Carimbo de data/hora', ascending=True)
data_sheet = data_sheet_raw.fillna("-") # data_sheet['Eu sou...'][6] = "Convidado"
data_sheet = data_sheet.loc[data_sheet["Carimbo de data/hora"] != '-']
data_sheet.head(len(data_sheet))

https://docs.google.com/spreadsheets/d/e/2PACX-1vToCjC7PtwrQtj6sNWHCmg6t_rH9R0CqHRlPhe3JqeurycvB1ETJ92mEbW0mub_n3L3Zl-Fz55yYSw5/pub?gid=419088388&single=true&output=csv

,Carimbo de data/hora,Eu sou...,Meu nome é...,Quer incluir um amigo?,Ele é...,Meu amigo é o....
0,19/06/2022 12:00:29,Veterano,JamiL,Não,-,-
1,19/06/2022 12:00:40,Veterano,Vitor Pessoa,Não,-,-
2,19/06/2022 12:01:45,Veterano,Gabriel Araújo,Não,-,-
3,19/06/2022 12:01:49,Veterano,Mateus A,Não,-,-
4,19/06/2022 12:05:14,Veterano,Pompeu,Não,-,-
5,19/06/2022 12:05:20,Veterano,Andre Teles,Não,-,-
6,19/06/2022 12:06:29,Veterano,Kalhil teles,Não,-,-
7,19/06/2022 12:06:55,Veterano,Italo,Não,-,-
8,19/06/2022 12:09:23,Veterano,Gabriel Bessa,Sim,Convidado,Kadu
9,19/06/2022 12:11:33,Veterano,Jp bessa,Não,-,-
10,19/06/2022 12:32:35,Veterano,Arlego,Não,-,-
11,19/06/2022 12:34:23,Veterano,Marcos jr,Não,-,-
12,19/06/2022 12:36:30,Veterano,Luciano,Não,-,-
13,19/06/2022 13:07:35,Veterano,George,Não,-,-

## Função para construir a lista

In [ ]:
# data_sheet.iloc[4,1] == "Veterano"
def build_list(df):
  list_main = []
  list_suplentes = []
  N = len(data_sheet) # <------ Get the list length automatically
  N_max = 30
  for ii in range(N):
    
    if ii < N_max:
      if data_sheet.iloc[ii,1] == "Veterano":
        list_main.append(data_sheet.iloc[ii,2])    
        if data_sheet.iloc[ii,3] == "Sim":
          if data_sheet.iloc[ii,4] == "Veterano":
            list_main.append(data_sheet.iloc[ii,5])
          else:
            list_suplentes.append(data_sheet.iloc[ii,5] + " ({})".format(data_sheet.iloc[ii,2])) # <------ Save the name associated (veterano)
      if data_sheet.iloc[ii,1] == "Convidado":
        list_suplentes.append(data_sheet.iloc[ii,2]) # <------ Save the name associated (veterano)
    else:
      list_suplentes.append(data_sheet.iloc[ii,2])

  return(list_main, list_suplentes)

def print_list(principal, suplentes, date):
  print("*Lista R9*\n{}\n{} bola ao centro\n\n*Goleiros*:\n1 - \n2 - \n\n*Jogadores*:".format(date, "*20h30*"))

  N_principal = len(principal);  

  
  '''
  Para imprimir 18, 24, ou 30 espaços usar o seguinte bloco.
  Comentar este bloco caso queira imprimir todos os 30 espaços
  '''
  if N_principal < 18: 
    N_max = 18
  elif N_principal > 18 and N_principal < 24:
    N_max = 24
  else:
    N_max = 30
  
  '''
  Para imprimir todos os 30 espaços basta descomentar a linha seguinte
  '''
  # N_max = 30

  # Formatacao da lista, posicao de inscricao na lista e nome do membro
  if N_principal != N_max: 
    for index in range(N_principal):
      print('{} - {}'.format(index+1, principal[index] ))
    for ii in range(N_max - N_principal):
      print('{} - '.format(N_principal+ii+1))
  
  # Lista de suplentes
  print("\n*Suplentes*:") 
  for index in range(len(suplentes)):
    print('{}'.format(suplentes[index]))

# Gerar a lista

In [ ]:
DATA_DO_RACHA = 'Quarta {:%d/%m}'.format(proxima_quarta) # <-------------------- DATA AUTOMATICA
print_list(build_list(data_sheet)[0], build_list(data_sheet)[1], date=DATA_DO_RACHA)

*Lista R9*
Quarta 22/06
*20h30* bola ao centro

*Goleiros*:
1 -
2 -

*Jogadores*:
1 - JamiL
2 - Vitor Pessoa
3 - Gabriel Araújo
4 - Mateus A
5 - Pompeu
6 - Andre Teles
7 - Kalhil teles
8 - Italo
9 - Gabriel Bessa
10 - Jp bessa
11 - Arlego
12 - Marcos jr
13 - Luciano
14 - George
15 -
16 -
17 -
18 -

*Suplentes*:
Kadu (Gabriel Bessa)